#! /bin/bash

PROGNAME=$0
TARGET_CLASSES_PATH="target/classes"
TARGET_PIT_REPORTS_EXPORT_PATH="target/pit-reports/export"

usage() {
    cat << EOF >&2
Usage: $PROGNAME [-m <mutant index>] <class name>

<class name>          Class name with dot syntax (e.g. com.cs453.group5.examples.Calculator)
-m <mutant index>     Mutant index. By default, this script will run the original one.

EOF
    exit 1
}

do_pit_if_necessary() {
    if [[ ! -e $TARGET_PIT_REPORTS_EXPORT_PATH ]]; then
        mvn org.pitest:pitest-maven:mutationCoverage -Dfeatures=+EXPORT
    elif [[ ! -d $TARGET_PIT_REPORTS_EXPORT_PATH ]]; then
        echo "$TARGET_PIT_REPORTS_EXPORT_PATH already exists but is not a directory." 1>&2
        exit 1
    fi

}

backup_original() {
    basename="${classname##*.}"
    src="$TARGET_CLASSES_PATH/${classname//./\/}.class"
    dest="$TARGET_PIT_REPORTS_EXPORT_PATH/${classname//./\/}/$basename.class"
    cp -n $src $dest
}

copy_mutant() {
    if [[ $mutant -eq -1 ]]
    then
        src="$TARGET_PIT_REPORTS_EXPORT_PATH/${classname//./\/}/$basename.class"
    else
        src="$TARGET_PIT_REPORTS_EXPORT_PATH/${classname//./\/}/mutants/$mutant/$classname.class"
    fi
    dest="$TARGET_CLASSES_PATH/${classname//./\/}.class"

    cp -rf $src $dest
}

mutant=-1
while getopts m: o; do
  case $o in
    (m) mutant=$OPTARG;;
    (*) usage
  esac
done
shift "$((OPTIND - 1))"
classname="$@"

if [[ -z $classname ]]
then
    usage
fi

do_pit_if_necessary
backup_original
copy_mutant
java -cp 'target/classes:res/jbse-0.10.0-SNAPSHOT-shaded.jar' \
     com.cs453.group5.examples.RunExample "${classname//./\/}"
